// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/msg_key.proto

package network.cosmos.listening.plugins.kafka.service;

public final class MsgKeyOuterClass {
  private MsgKeyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MsgKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MsgKey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/msg_key.proto\"\262\002\n\006MsgKey\022\"\n\014bloc" +
      "k_height\030\001 \001(\003R\014block_height\022\034\n\005event\030\002 " +
      "\001(\0162\r.MsgKey.Event\022\032\n\010event_id\030\003 \001(\003R\010ev" +
      "ent_id\0221\n\nevent_type\030\004 \001(\0162\021.MsgKey.Even" +
      "tTypeR\nevent_type\022$\n\revent_type_id\030\005 \001(\003" +
      "R\revent_type_id\"7\n\005Event\022\017\n\013BEGIN_BLOCK\020" +
      "\000\022\r\n\tEND_BLOCK\020\001\022\016\n\nDELIVER_TX\020\002\"8\n\tEven" +
      "tType\022\013\n\007REQUEST\020\000\022\014\n\010RESPONSE\020\001\022\020\n\014STAT" +
      "E_CHANGE\020\002Bm\n.network.cosmos.listening.p" +
      "lugins.kafka.serviceP\001Z9github.com/cosmo" +
      "s/cosmos-sdk/plugin/plugins/kafka/servic" +
      "eb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MsgKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MsgKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MsgKey_descriptor,
        new java.lang.String[] { "BlockHeight", "Event", "EventId", "EventType", "EventTypeId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
