// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/msg_key.proto

package io.provenance.statelistening.kafka.protobuf.serializer;

public final class MsgKeyOuterClass {
  private MsgKeyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_provenance_statelistening_kafka_protobuf_serializer_MsgKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_provenance_statelistening_kafka_protobuf_serializer_MsgKey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/msg_key.proto\0223provenance.statel" +
      "istening.kafka.protobuf.serializer\"\232\003\n\006M" +
      "sgKey\022\"\n\014block_height\030\001 \001(\003R\014block_heigh" +
      "t\022P\n\005event\030\002 \001(\0162A.provenance.stateliste" +
      "ning.kafka.protobuf.serializer.MsgKey.Ev" +
      "ent\022\032\n\010event_id\030\003 \001(\003R\010event_id\022e\n\nevent" +
      "_type\030\004 \001(\0162E.provenance.statelistening." +
      "kafka.protobuf.serializer.MsgKey.EventTy" +
      "peR\nevent_type\022$\n\revent_type_id\030\005 \001(\003R\re" +
      "vent_type_id\"7\n\005Event\022\017\n\013BEGIN_BLOCK\020\000\022\r" +
      "\n\tEND_BLOCK\020\001\022\016\n\nDELIVER_TX\020\002\"8\n\tEventTy" +
      "pe\022\013\n\007REQUEST\020\000\022\014\n\010RESPONSE\020\001\022\020\n\014STATE_C" +
      "HANGE\020\002B:\n6io.provenance.statelistening." +
      "kafka.protobuf.serializerP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_provenance_statelistening_kafka_protobuf_serializer_MsgKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_provenance_statelistening_kafka_protobuf_serializer_MsgKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_provenance_statelistening_kafka_protobuf_serializer_MsgKey_descriptor,
        new java.lang.String[] { "BlockHeight", "Event", "EventId", "EventType", "EventTypeId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
