// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/msg_key.proto

package io.provenance.statelistening.kafka.protobuf.serializer;

public interface MsgKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:provenance.statelistening.kafka.protobuf.serializer.MsgKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 block_height = 1 [json_name = "block_height"];</code>
   * @return The blockHeight.
   */
  long getBlockHeight();

  /**
   * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event event = 2;</code>
   * @return The enum numeric value on the wire for event.
   */
  int getEventValue();
  /**
   * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event event = 2;</code>
   * @return The event.
   */
  io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event getEvent();

  /**
   * <code>int64 event_id = 3 [json_name = "event_id"];</code>
   * @return The eventId.
   */
  long getEventId();

  /**
   * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType event_type = 4 [json_name = "event_type"];</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType event_type = 4 [json_name = "event_type"];</code>
   * @return The eventType.
   */
  io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType getEventType();

  /**
   * <code>int64 event_type_id = 5 [json_name = "event_type_id"];</code>
   * @return The eventTypeId.
   */
  long getEventTypeId();
}
