// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/msg_key.proto

package io.provenance.statelistening.kafka.protobuf.serializer;

/**
 * Protobuf type {@code provenance.statelistening.kafka.protobuf.serializer.MsgKey}
 */
public final class MsgKey extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:provenance.statelistening.kafka.protobuf.serializer.MsgKey)
    MsgKeyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MsgKey.newBuilder() to construct.
  private MsgKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MsgKey() {
    event_ = 0;
    eventType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MsgKey();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MsgKey(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            blockHeight_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            event_ = rawValue;
            break;
          }
          case 24: {

            eventId_ = input.readInt64();
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            eventType_ = rawValue;
            break;
          }
          case 40: {

            eventTypeId_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.provenance.statelistening.kafka.protobuf.serializer.MsgKeyOuterClass.internal_static_provenance_statelistening_kafka_protobuf_serializer_MsgKey_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.provenance.statelistening.kafka.protobuf.serializer.MsgKeyOuterClass.internal_static_provenance_statelistening_kafka_protobuf_serializer_MsgKey_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.class, io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Builder.class);
  }

  /**
   * Protobuf enum {@code provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event}
   */
  public enum Event
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BEGIN_BLOCK = 0;</code>
     */
    BEGIN_BLOCK(0),
    /**
     * <code>END_BLOCK = 1;</code>
     */
    END_BLOCK(1),
    /**
     * <code>DELIVER_TX = 2;</code>
     */
    DELIVER_TX(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BEGIN_BLOCK = 0;</code>
     */
    public static final int BEGIN_BLOCK_VALUE = 0;
    /**
     * <code>END_BLOCK = 1;</code>
     */
    public static final int END_BLOCK_VALUE = 1;
    /**
     * <code>DELIVER_TX = 2;</code>
     */
    public static final int DELIVER_TX_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Event valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Event forNumber(int value) {
      switch (value) {
        case 0: return BEGIN_BLOCK;
        case 1: return END_BLOCK;
        case 2: return DELIVER_TX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Event>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Event> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Event>() {
            public Event findValueByNumber(int number) {
              return Event.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.getDescriptor().getEnumTypes().get(0);
    }

    private static final Event[] VALUES = values();

    public static Event valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Event(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event)
  }

  /**
   * Protobuf enum {@code provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQUEST = 0;</code>
     */
    REQUEST(0),
    /**
     * <code>RESPONSE = 1;</code>
     */
    RESPONSE(1),
    /**
     * <code>STATE_CHANGE = 2;</code>
     */
    STATE_CHANGE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>REQUEST = 0;</code>
     */
    public static final int REQUEST_VALUE = 0;
    /**
     * <code>RESPONSE = 1;</code>
     */
    public static final int RESPONSE_VALUE = 1;
    /**
     * <code>STATE_CHANGE = 2;</code>
     */
    public static final int STATE_CHANGE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return REQUEST;
        case 1: return RESPONSE;
        case 2: return STATE_CHANGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.getDescriptor().getEnumTypes().get(1);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType)
  }

  public static final int BLOCK_HEIGHT_FIELD_NUMBER = 1;
  private long blockHeight_;
  /**
   * <code>int64 block_height = 1 [json_name = "block_height"];</code>
   * @return The blockHeight.
   */
  @java.lang.Override
  public long getBlockHeight() {
    return blockHeight_;
  }

  public static final int EVENT_FIELD_NUMBER = 2;
  private int event_;
  /**
   * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event event = 2;</code>
   * @return The enum numeric value on the wire for event.
   */
  @java.lang.Override public int getEventValue() {
    return event_;
  }
  /**
   * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event event = 2;</code>
   * @return The event.
   */
  @java.lang.Override public io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event getEvent() {
    @SuppressWarnings("deprecation")
    io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event result = io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event.valueOf(event_);
    return result == null ? io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event.UNRECOGNIZED : result;
  }

  public static final int EVENT_ID_FIELD_NUMBER = 3;
  private long eventId_;
  /**
   * <code>int64 event_id = 3 [json_name = "event_id"];</code>
   * @return The eventId.
   */
  @java.lang.Override
  public long getEventId() {
    return eventId_;
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 4;
  private int eventType_;
  /**
   * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType event_type = 4 [json_name = "event_type"];</code>
   * @return The enum numeric value on the wire for eventType.
   */
  @java.lang.Override public int getEventTypeValue() {
    return eventType_;
  }
  /**
   * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType event_type = 4 [json_name = "event_type"];</code>
   * @return The eventType.
   */
  @java.lang.Override public io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType getEventType() {
    @SuppressWarnings("deprecation")
    io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType result = io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType.valueOf(eventType_);
    return result == null ? io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType.UNRECOGNIZED : result;
  }

  public static final int EVENT_TYPE_ID_FIELD_NUMBER = 5;
  private long eventTypeId_;
  /**
   * <code>int64 event_type_id = 5 [json_name = "event_type_id"];</code>
   * @return The eventTypeId.
   */
  @java.lang.Override
  public long getEventTypeId() {
    return eventTypeId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (blockHeight_ != 0L) {
      output.writeInt64(1, blockHeight_);
    }
    if (event_ != io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event.BEGIN_BLOCK.getNumber()) {
      output.writeEnum(2, event_);
    }
    if (eventId_ != 0L) {
      output.writeInt64(3, eventId_);
    }
    if (eventType_ != io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType.REQUEST.getNumber()) {
      output.writeEnum(4, eventType_);
    }
    if (eventTypeId_ != 0L) {
      output.writeInt64(5, eventTypeId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (blockHeight_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, blockHeight_);
    }
    if (event_ != io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event.BEGIN_BLOCK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, event_);
    }
    if (eventId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, eventId_);
    }
    if (eventType_ != io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType.REQUEST.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, eventType_);
    }
    if (eventTypeId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, eventTypeId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.provenance.statelistening.kafka.protobuf.serializer.MsgKey)) {
      return super.equals(obj);
    }
    io.provenance.statelistening.kafka.protobuf.serializer.MsgKey other = (io.provenance.statelistening.kafka.protobuf.serializer.MsgKey) obj;

    if (getBlockHeight()
        != other.getBlockHeight()) return false;
    if (event_ != other.event_) return false;
    if (getEventId()
        != other.getEventId()) return false;
    if (eventType_ != other.eventType_) return false;
    if (getEventTypeId()
        != other.getEventTypeId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOCK_HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockHeight());
    hash = (37 * hash) + EVENT_FIELD_NUMBER;
    hash = (53 * hash) + event_;
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEventId());
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + eventType_;
    hash = (37 * hash) + EVENT_TYPE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEventTypeId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.provenance.statelistening.kafka.protobuf.serializer.MsgKey prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code provenance.statelistening.kafka.protobuf.serializer.MsgKey}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:provenance.statelistening.kafka.protobuf.serializer.MsgKey)
      io.provenance.statelistening.kafka.protobuf.serializer.MsgKeyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.provenance.statelistening.kafka.protobuf.serializer.MsgKeyOuterClass.internal_static_provenance_statelistening_kafka_protobuf_serializer_MsgKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.provenance.statelistening.kafka.protobuf.serializer.MsgKeyOuterClass.internal_static_provenance_statelistening_kafka_protobuf_serializer_MsgKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.class, io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Builder.class);
    }

    // Construct using io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      blockHeight_ = 0L;

      event_ = 0;

      eventId_ = 0L;

      eventType_ = 0;

      eventTypeId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.provenance.statelistening.kafka.protobuf.serializer.MsgKeyOuterClass.internal_static_provenance_statelistening_kafka_protobuf_serializer_MsgKey_descriptor;
    }

    @java.lang.Override
    public io.provenance.statelistening.kafka.protobuf.serializer.MsgKey getDefaultInstanceForType() {
      return io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.getDefaultInstance();
    }

    @java.lang.Override
    public io.provenance.statelistening.kafka.protobuf.serializer.MsgKey build() {
      io.provenance.statelistening.kafka.protobuf.serializer.MsgKey result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.provenance.statelistening.kafka.protobuf.serializer.MsgKey buildPartial() {
      io.provenance.statelistening.kafka.protobuf.serializer.MsgKey result = new io.provenance.statelistening.kafka.protobuf.serializer.MsgKey(this);
      result.blockHeight_ = blockHeight_;
      result.event_ = event_;
      result.eventId_ = eventId_;
      result.eventType_ = eventType_;
      result.eventTypeId_ = eventTypeId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.provenance.statelistening.kafka.protobuf.serializer.MsgKey) {
        return mergeFrom((io.provenance.statelistening.kafka.protobuf.serializer.MsgKey)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.provenance.statelistening.kafka.protobuf.serializer.MsgKey other) {
      if (other == io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.getDefaultInstance()) return this;
      if (other.getBlockHeight() != 0L) {
        setBlockHeight(other.getBlockHeight());
      }
      if (other.event_ != 0) {
        setEventValue(other.getEventValue());
      }
      if (other.getEventId() != 0L) {
        setEventId(other.getEventId());
      }
      if (other.eventType_ != 0) {
        setEventTypeValue(other.getEventTypeValue());
      }
      if (other.getEventTypeId() != 0L) {
        setEventTypeId(other.getEventTypeId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.provenance.statelistening.kafka.protobuf.serializer.MsgKey parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.provenance.statelistening.kafka.protobuf.serializer.MsgKey) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long blockHeight_ ;
    /**
     * <code>int64 block_height = 1 [json_name = "block_height"];</code>
     * @return The blockHeight.
     */
    @java.lang.Override
    public long getBlockHeight() {
      return blockHeight_;
    }
    /**
     * <code>int64 block_height = 1 [json_name = "block_height"];</code>
     * @param value The blockHeight to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHeight(long value) {
      
      blockHeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 block_height = 1 [json_name = "block_height"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockHeight() {
      
      blockHeight_ = 0L;
      onChanged();
      return this;
    }

    private int event_ = 0;
    /**
     * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event event = 2;</code>
     * @return The enum numeric value on the wire for event.
     */
    @java.lang.Override public int getEventValue() {
      return event_;
    }
    /**
     * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event event = 2;</code>
     * @param value The enum numeric value on the wire for event to set.
     * @return This builder for chaining.
     */
    public Builder setEventValue(int value) {
      
      event_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event event = 2;</code>
     * @return The event.
     */
    @java.lang.Override
    public io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event getEvent() {
      @SuppressWarnings("deprecation")
      io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event result = io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event.valueOf(event_);
      return result == null ? io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event.UNRECOGNIZED : result;
    }
    /**
     * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event event = 2;</code>
     * @param value The event to set.
     * @return This builder for chaining.
     */
    public Builder setEvent(io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      event_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.Event event = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEvent() {
      
      event_ = 0;
      onChanged();
      return this;
    }

    private long eventId_ ;
    /**
     * <code>int64 event_id = 3 [json_name = "event_id"];</code>
     * @return The eventId.
     */
    @java.lang.Override
    public long getEventId() {
      return eventId_;
    }
    /**
     * <code>int64 event_id = 3 [json_name = "event_id"];</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(long value) {
      
      eventId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 event_id = 3 [json_name = "event_id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      
      eventId_ = 0L;
      onChanged();
      return this;
    }

    private int eventType_ = 0;
    /**
     * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType event_type = 4 [json_name = "event_type"];</code>
     * @return The enum numeric value on the wire for eventType.
     */
    @java.lang.Override public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType event_type = 4 [json_name = "event_type"];</code>
     * @param value The enum numeric value on the wire for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeValue(int value) {
      
      eventType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType event_type = 4 [json_name = "event_type"];</code>
     * @return The eventType.
     */
    @java.lang.Override
    public io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType getEventType() {
      @SuppressWarnings("deprecation")
      io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType result = io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType.valueOf(eventType_);
      return result == null ? io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType.UNRECOGNIZED : result;
    }
    /**
     * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType event_type = 4 [json_name = "event_type"];</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(io.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      eventType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.provenance.statelistening.kafka.protobuf.serializer.MsgKey.EventType event_type = 4 [json_name = "event_type"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      
      eventType_ = 0;
      onChanged();
      return this;
    }

    private long eventTypeId_ ;
    /**
     * <code>int64 event_type_id = 5 [json_name = "event_type_id"];</code>
     * @return The eventTypeId.
     */
    @java.lang.Override
    public long getEventTypeId() {
      return eventTypeId_;
    }
    /**
     * <code>int64 event_type_id = 5 [json_name = "event_type_id"];</code>
     * @param value The eventTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeId(long value) {
      
      eventTypeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 event_type_id = 5 [json_name = "event_type_id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEventTypeId() {
      
      eventTypeId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:provenance.statelistening.kafka.protobuf.serializer.MsgKey)
  }

  // @@protoc_insertion_point(class_scope:provenance.statelistening.kafka.protobuf.serializer.MsgKey)
  private static final io.provenance.statelistening.kafka.protobuf.serializer.MsgKey DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.provenance.statelistening.kafka.protobuf.serializer.MsgKey();
  }

  public static io.provenance.statelistening.kafka.protobuf.serializer.MsgKey getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MsgKey>
      PARSER = new com.google.protobuf.AbstractParser<MsgKey>() {
    @java.lang.Override
    public MsgKey parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MsgKey(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MsgKey> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MsgKey> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.provenance.statelistening.kafka.protobuf.serializer.MsgKey getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

